### ISSUE TITLE
look at awesome/wordlists

### ISSUE THREAD

**Issue by ccoVeille** [jargonLint/jargonLint#14]
Some sources may be interesting to consider https://github.com/gmelodie/awesome-wordlists

**Comment by ccoVeille** [comment]
I'm unsure why you quote a repository while the site is about bunch projects

**Comment by ccoVeille** [comment]
I get it now, @alexvonme I think your comment was for 
- https://github.com/jargonLint/jargonLint/issues/12

**Comment by alexvonme** [comment]
Moved to #31
