### ISSUE TITLE
Update the README file to add information about existing style guide

### ISSUE THREAD

**Issue by ccoVeille** [jargonLint/jargonLint#19]
> we should add links to certain style guides, especially to SUSE and Red Hat. I'm only delaying it for now because I want to add a few things to the repository beforehand.

_Originally posted by @alexvonme in https://github.com/jargonLint/jargonLint/pull/18#discussion_r1655220830_

**Comment by ccoVeille** [comment]
I played with a feature I don't understand yet 👆

**Comment by ccoVeille** [comment]
the issue was about this

> we should add links to certain style guides, especially to SUSE and Red Hat. I'm only delaying it for now because I want to add a few things to the repository beforehand.

We didn't do it.

I was only reporting I played with "issue relationship" and event were logged on this issues

**Comment by alexvonme** [comment]
I thought, I could close this for now since we'd agreed to indefinitely delay it. I hope #30 is sufficient for now.
