### ISSUE TITLE
Add a Contribution page

### ISSUE THREAD

**Issue by ccoVeille** [jargonLint/jargonLint#20]

**Comment by ccoVeille** [comment]
This page should of course how to contribute to the project, but it must tall about the tools and available tooling/helper scripts to use to collaborate.

Because with the addition I plan with 

- #15

to import all the tools I used for

- https://github.com/ccoVeille/golangci-lint-config-examples/pull/7

and because of the tooling we need if we build the `Technology.yaml` section from
- #16

These might be done as a part of be a part #15 issues, BTW

But I thought it would make to talk about it here

**Comment by alexvonme** [comment]
#45 added the template and the general recommendations, we can close this issue after you add the CI tool explanations.
