### ISSUE TITLE
Consider content from XforYgen

### ISSUE THREAD

**Issue by ccoVeille** [jargonLint/jargonLint#21]
https://github.com/cupOJoseph/XforYgen
MIT License

This is a random words generator. It uses list of brands available in a file:
https://github.com/cupOJoseph/XforYgen/blob/master/X.txt

**Comment by alexvonme** [comment]
I don't think this one is very useful. It's too general purpose, and we should probably not involve lists that haven't had a clear methodology in their formation.

It does look fun, but I think we shouldn't use it.
