### ISSUE TITLE
Consider content from shields.io

### ISSUE THREAD

**Issue by ccoVeille** [jargonLint/jargonLint#23]
https://github.com/badges/shields
License: CC0-1.0

I have never heard about this license

This repository is interesting as it content a lot of ecosystem tooling terms

**Comment by alexvonme** [comment]
It seems relatively safe from the [deed](https://creativecommons.org/publicdomain/zero/1.0/deed.en). Though I'm not an expert myself, we can ask someone else if you're hesitant.

**Comment by alexvonme** [comment]
Moved to #31
