### ISSUE TITLE
Consider looking at RedHat tooling

### ISSUE THREAD

**Issue by ccoVeille** [jargonLint/jargonLint#25]
https://github.com/redhat-documentation/vale-at-red-hat/blob/main/tools/vale_report.sh

License: Eclipse Public License 2.0

There are things we could inspire from

_Originally posted by @aireilly in https://github.com/redhat-documentation/vale-at-red-hat/issues/815#issuecomment-2194703242_

**Comment by alexvonme** [comment]
This one's copylefted so we can't take it directly but indeed a good source of inspiration

**Comment by ccoVeille** [comment]
I assumed it, yes.
