### ISSUE TITLE
Consider adding content from alexandresanlim/Badges4-README.md-Profile

### ISSUE THREAD

**Issue by ccoVeille** [jargonLint/jargonLint#28]
https://github.com/alexandresanlim/Badges4-README.md-Profile
License: not provided

**Comment by ccoVeille** [comment]
I opened the following issue to ask owner to create a license

- https://github.com/alexandresanlim/Badges4-README.md-Profile/issues/674

**Comment by alexvonme** [comment]
Moved to #31
