### ISSUE TITLE
Look at libraries.api

### ISSUE THREAD

**Issue by ccoVeille** [jargonLint/jargonLint#5]
https://libraries.io/api

It may provide valuable resources of words and cases. Somehow, what I wanted to achieve. Parsing the API results into yaml list could be interesting

https://github.com/librariesio/libraries.io

License of the DATA: CC-BY-4.0 https://libraries.io/terms

**Comment by ccoVeille** [comment]
This lib might be interesting even if code is very old

https://github.com/hackebrot/go-librariesio

**Comment by alexvonme** [comment]
Moved to #31
