### ISSUE TITLE
Add content from glossario

### ISSUE THREAD

**Issue by ccoVeille** [jargonLint/jargonLint#8]
https://github.com/carpentries/glosario

License: CC-BY-4.0

**Comment by ccoVeille** [comment]
I need to check if this license is OK to integrate the data

**Comment by ccoVeille** [comment]
Seems it would be "OK"

https://opensource.stackexchange.com/questions/6110/is-there-any-particular-reason-to-license-docs-with-cc-by-4-0-rather-than-mit

What are your thoughts @Jason3S ?

**Comment by alexvonme** [comment]
Moved to #31
