### ISSUE TITLE
Write a descent readme

### ISSUE THREAD

**Issue by ccoVeille** [jargonLint/jargonLint#9]
It should be clearer to everyone what I try to avjibe with this project

Content could be copy pasted from

- #1
- #2
- #3
- https://github.com/ccoVeille/jargon/pull/4#issuecomment-2184979546

**Comment by alexvonme** [comment]
I can propose something tomorrow and possibly tag someone to review it.

**Comment by ccoVeille** [comment]
I was thinking about using something close to what can be found on the suze-vale-styleguide.

Without the how to install for now. It may be added later when project will be more mature
